# Generated by Django 4.2.1 on 2023-07-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_category_slug_alter_post_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='minute_read',
            new_name='readtime',
        ),
    ]
