# Generated by Django 4.2.1 on 2023-12-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_outline_postoutline_text_postsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('new', 'New'), ('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=100),
        ),
    ]
