# Generated by Django 4.2.1 on 2023-12-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRephraseSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('segment_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostRephrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('shadowText', models.CharField(blank=True, max_length=300, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=400, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('html', models.TextField()),
                ('current_segment', models.IntegerField()),
                ('rephrased_content', models.TextField(blank=True, null=True)),
                ('segments', models.ManyToManyField(blank=True, to='posts.postrephrasesegment')),
            ],
        ),
    ]
