# Generated by Django 4.2.1 on 2023-07-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_minute_read_post_readtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readtime',
            field=models.CharField(max_length=20),
        ),
    ]
