# Generated by Django 4.2.1 on 2023-07-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_readtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readtime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
