# Generated by Django 4.2.1 on 2023-12-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postrephrasesegment_postrephrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrephrase',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
