# Generated by Django 4.2.1 on 2023-07-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_readtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/'),
        ),
    ]
