# Generated by Django 4.2.1 on 2024-01-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postideaurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIdeaSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('segment_index', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='postideaurl',
            name='segments',
        ),
        migrations.AddField(
            model_name='postideaurl',
            name='segments',
            field=models.ManyToManyField(blank=True, to='posts.postideasegment'),
        ),
    ]
