# Generated by Django 4.2.1 on 2023-07-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_featured_image_post_post_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='posttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_type_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tag_images/%Y/%m/%d/'),
        ),
    ]
