# Generated by Django 4.2.1 on 2023-09-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_customfieldvalue_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='light', max_length=100),
        ),
    ]
