# Generated by Django 4.2.1 on 2023-10-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_seo_keywords_alter_post_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='featured_images/%Y/%m/%d/')),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='featured_images/thumbnail/%Y/%m/%d/')),
                ('medium', models.ImageField(blank=True, null=True, upload_to='featured_images/medium/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='optimized_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.featuredimage'),
        ),
    ]
