# Generated by Django 4.2.1 on 2023-07-26 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 26, 9, 44, 19, 851148, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
