# Generated by Django 4.2.1 on 2023-08-03 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_alter_post_headline_alter_post_shadowtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('black', 'Black'), ('white', 'White'), ('magenta', 'Magenta'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('lime', 'Lime'), ('amber', 'Amber')], default='draft', max_length=100),
        ),
        migrations.AddField(
            model_name='posttype',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('black', 'Black'), ('white', 'White'), ('magenta', 'Magenta'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('lime', 'Lime'), ('amber', 'Amber')], default='draft', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('black', 'Black'), ('white', 'White'), ('magenta', 'Magenta'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('lime', 'Lime'), ('amber', 'Amber')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('black', 'Black'), ('white', 'White'), ('magenta', 'Magenta'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('lime', 'Lime'), ('amber', 'Amber')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
        ),
    ]
