# Generated by Django 4.2.1 on 2023-08-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_category_color_posttype_color_tag_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='posttype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='posttype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
    ]
