# Generated by Django 4.2.1 on 2023-08-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_category_color_remove_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='shadowText',
            new_name='shadow_text',
        ),
    ]
