# Generated by Django 4.2.1 on 2023-09-21 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_address_useraccount_amazon_associate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
