# Generated by Django 4.2.1 on 2023-10-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('SUBSCRIBER', 'Subscriber'), ('TRIAL', 'Trial'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise'), ('ADMIN', 'Admin')], default='SUBSCRIBER', max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
