# Generated by Django 4.2.1 on 2023-10-31 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_useraccount_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='account_active',
        ),
    ]
