# Generated by Django 4.2.1 on 2023-11-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_useraccount_account_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_active',
            field=models.BooleanField(default=True),
        ),
    ]
