# Generated by Django 4.2.1 on 2023-11-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_last_updated_productlist'),
        ('users', '0009_useraccount_account_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='product_lists',
            field=models.ManyToManyField(blank=True, to='products.productlist'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
