# Generated by Django 4.2.1 on 2023-09-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bot_type', models.CharField(choices=[('gpt3.5-turbo', 'GPT3.5 Turbo'), ('gpt3.5', 'GPT3.5'), ('gpt4', 'GPT4')], default='gpt3.5-turbo', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openai.room')),
            ],
        ),
    ]
