# Generated by Django 4.2.1 on 2023-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_email',
            field=models.CharField(default='rwchampin@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_email',
            field=models.CharField(default='rwchampin@gmail.com', max_length=255),
        ),
    ]
