# Generated by Django 4.2.1 on 2023-08-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
