# Generated by Django 4.2.1 on 2023-10-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0002_registrant_first_name_registrant_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
