# Generated by Django 4.2.1 on 2023-10-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0003_alter_registrant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email is required', 'unique': 'Email already exists'}, max_length=254, unique=True),
        ),
    ]
