# Generated by Django 4.2.1 on 2023-09-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinglist',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
