# Generated by Django 4.2.1 on 2023-09-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketinglist_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinglist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
