# Generated by Django 4.2.1 on 2023-09-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketinglist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketinglist',
            name='slug',
        ),
        migrations.AddField(
            model_name='marketinglist',
            name='url',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
