# Generated by Django 4.2.1 on 2023-09-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_remove_marketinglist_slug_marketinglist_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='niche',
        ),
        migrations.RemoveField(
            model_name='marketinglist',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='marketinglist',
            name='niche',
        ),
        migrations.RemoveField(
            model_name='marketinglist',
            name='tags',
        ),
        migrations.AddField(
            model_name='email',
            name='niches',
            field=models.ManyToManyField(related_name='emails', to='marketing.niche'),
        ),
        migrations.AddField(
            model_name='marketinglist',
            name='niches',
            field=models.ManyToManyField(related_name='marketing_lists', to='marketing.niche'),
        ),
        migrations.AddField(
            model_name='tag',
            name='niches',
            field=models.ManyToManyField(related_name='tags', to='marketing.niche'),
        ),
    ]
