# Generated by Django 4.2.1 on 2023-10-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_listtype_delete_datasource_remove_email_niches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketinglist',
            name='url',
        ),
        migrations.AlterField(
            model_name='listtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketinglist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketinglist',
            name='emails',
            field=models.ManyToManyField(blank=True, null=True, related_name='marketing_list_emails', to='marketing.email'),
        ),
        migrations.AlterField(
            model_name='marketinglist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketinglist',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='marketing.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
