# Generated by Django 4.2.1 on 2023-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_remove_marketinglist_url_alter_listtype_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinglist',
            name='downloaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketinglist',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='marketing_list_emails', to='marketing.email'),
        ),
        migrations.AlterField(
            model_name='marketinglist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='marketing.tag'),
        ),
    ]
