# Generated by Django 4.2.1 on 2023-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_marketinglist_downloaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinglist',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketinglist',
            name='is_populating',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='marketinglist',
            name='limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
