# Generated by Django 4.2.1 on 2023-07-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_percent', models.FloatField()),
                ('uptime_try_count', models.PositiveIntegerField()),
                ('uptime_success_count', models.PositiveIntegerField()),
                ('uptime', models.FloatField()),
                ('updated_at', models.DateTimeField()),
                ('speed', models.FloatField()),
                ('response_time', models.FloatField()),
                ('region', models.CharField(max_length=100)),
                ('anonymity_level', models.CharField(max_length=100)),
                ('protocols', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
                ('org', models.CharField(max_length=100)),
                ('latency', models.FloatField()),
                ('last_checked', models.DateTimeField()),
                ('isp', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('google', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('asn', models.CharField(max_length=100)),
            ],
        ),
    ]
