# Generated by Django 4.2.1 on 2023-07-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='anonymity_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='org',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='working_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
