# Generated by Django 4.2.1 on 2023-12-03 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_assistantmodel_alter_assistant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmodel',
            name='model_created',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantmodel',
            name='model_object',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantmodel',
            name='model_owned_by',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assistantmodel',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
