# Generated by Django 4.2.1 on 2023-12-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_assistantmodel_model_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='model',
            field=models.ForeignKey(blank=True, error_messages={'blank': 'Please select a model', 'null': 'Please select a model'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_models', to='ai.assistantmodel'),
        ),
    ]
