# Generated by Django 4.2.1 on 2023-12-03 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0006_assistant_primary_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='assistant',
            field=models.ForeignKey(blank=True, error_messages={'blank': 'Please select an assistant', 'null': 'Please select an assistant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='ai.assistant'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(blank=True, error_messages={'blank': 'Please select a user', 'null': 'Please select a user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
