# Generated by Django 4.2.1 on 2023-12-03 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0007_chatroom_assistant_chatroom_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chatroom',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(related_name='chat_messages', to='ai.chatmessage'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('assistant', 'user')},
        ),
    ]
