# Generated by Django 4.2.1 on 2023-09-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reviews', models.IntegerField()),
                ('images', models.JSONField()),
                ('availability', models.BooleanField()),
                ('variants', models.JSONField()),
            ],
        ),
    ]
