# Generated by Django 4.2.1 on 2023-12-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='products',
        ),
        migrations.RemoveField(
            model_name='searchurl',
            name='products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductList',
        ),
        migrations.DeleteModel(
            name='SearchURL',
        ),
    ]
