# Generated by Django 4.2.1 on 2023-12-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchurl',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
    ]
